package epfg;

/**
 * This class provides the types that will be need to be loaded from
 * language-dependent XML files.
 * 
 * @author Seunghyuk Sean Choi
 */
public enum LanguagePropertyType {
    // TITLE FOR WINDOW TITLE BAR
    // TITLE FOR WINDOW TITLE BAR
    TITLE_WINDOW,
    
    // APPLICATION TOOLTIPS FOR BUTTONS
    TOOLTIP_NEW_EPORTFOLIO,
    TOOLTIP_LOAD_EPORTFOLIO,
    TOOLTIP_SAVE_EPORTFOLIO,
    TOOLTIP_VIEW_EPORTFOLIO,
    TOOLTIP_EXIT,
    TOOLTIP_ADD_PAGE,
    TOOLTIP_REMOVE_PAGE,
    TOOLTIP_MOVE_UP,
    TOOLTIP_MOVE_DOWN,
    TOOLTIP_PREVIOUS_SLIDE,
    TOOLTIP_NEXT_SLIDE,
    
    // DEFAULT VALUES
    DEFAULT_IMAGE_CAPTION,
    DEFAULT_EPORTFOLIO_TITLE,
    
    // UI LABELS
    TITLE_MODIFIER_WINDOW,
    TITLE_MODIFIER_HEADER,
    /* THESE ARE FOR LANGUAGE-DEPENDENT ERROR HANDLING,
     LIKE FOR TEXT PUT INTO DIALOG BOXES TO NOTIFY
     THE USER WHEN AN ERROR HAS OCCURED */
    ERROR_DATA_FILE_LOADING,
    ERROR_PROPERTIES_FILE_LOADING,
    ERROR_OCCURED,
    IMAGE_MISSING,
    VIDEO_MISSING,
    SAVE_PROMPT,
    YES_SELECTION,
    NO_SELECTION,
    CANCEL_SELECTION,
    LOAD_FAILED,
    CONGRATURATION,
    SLIDESHOW_DIALOG,
    CREATED_MESSAGE,
    ERROR_TITLE
}
